# Generated by Django 4.1.6 on 2023-02-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp_home',
            new_name='Emp',
        ),
    ]
