# Generated by Django 4.1.6 on 2023-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
